const state={stories:[],filter:'Alle'};const dialog=document.querySelector('#storyDialog');const LIVE_DATA_URL='https://raw.githubusercontent.com/pedersenalexsander-gif/narvik-brief/main/data/news.json';const LAST_VISIT_KEY='alexBriefLastVisit';const lastVisit=Number(localStorage.getItem(LAST_VISIT_KEY)||0);const hour=new Date().getHours();document.querySelector('#greeting').textContent=hour<11?'GOD MORGEN':hour<17?'GOD ETTERMIDDAG':'GOD KVELD';
const LOW_VALUE=['wetherspoon','school uniform','uniform bank','tohodet slange','to-headed snake','utstilling','konsertplakat','pubs','music from phones','quiz','kjendis','celebrity','horoscope','lotteri','festival','restaurant review'];
function relativeTime(iso,fallback=''){if(!iso)return fallback;const mins=Math.max(0,Math.floor((Date.now()-new Date(iso).getTime())/60000));if(mins<60)return mins<=1?'Nå':`${mins} min siden`;const hours=Math.floor(mins/60);if(hours<24)return`${hours} t siden`;return`${Math.floor(hours/24)} d siden`}
function readTime(s){const w=`${s.summary||''} ${(s.keyPoints||[]).join(' ')}`.trim().split(/\s+/).length;return`${Math.max(1,Math.ceil(w/180))} min oversikt`}
function isNew(s){return lastVisit>0&&new Date(s.publishedISO||0).getTime()>lastVisit}
function localImageUrl(s){if(!s.localImage)return'';return new URL(s.localImage.replace(/^\//,''),document.baseURI).href}
function setImage(img,wrap,story){const url=localImageUrl(story);if(!img||!wrap||!url){if(wrap)wrap.classList.add('no-image');return}img.alt=`Bilde fra saken: ${displayTitle(story)}`;img.onload=()=>{img.style.display='block';wrap.classList.remove('no-image')};img.onerror=()=>{img.style.display='none';wrap.classList.add('no-image')};img.src=url}
function looksEnglish(t=''){const x=` ${t.toLowerCase()} `;const hits=[' the ',' and ',' with ',' from ',' after ',' customers ',' school ',' says ',' said ',' has ',' have ',' playing ',' demand ',' bans ',' never ',' higher ',' pub ',' phone ',' music ',' government ',' market ',' company ',' people ',' new '].filter(w=>x.includes(w)).length;return hits>=1&&/[a-z]/.test(t)}
function sentenceTitle(t=''){let s=(t||'').split(/(?<=[.!?])\s/)[0].replace(/[“”"']/g,'').trim();if(s.length>92)s=s.slice(0,89).replace(/\s+\S*$/,'')+'…';return s}
function displayTitle(s){if(!looksEnglish(s.title))return s.title;const no=sentenceTitle(s.summary);return no&&!looksEnglish(no)?no:'Internasjonal utvikling – kort forklart på norsk'}
function isLowValue(s){const hay=`${s.title||''} ${s.summary||''}`.toLowerCase();return LOW_VALUE.some(x=>hay.includes(x))}
function usableStory(s){return !!s.localImage&&!isLowValue(s)}
function openStory(s){const title=displayTitle(s);document.querySelector('#dialogTag').textContent=s.category;document.querySelector('#dialogTime').textContent=`${relativeTime(s.publishedISO,s.published)} · ${readTime(s)}`;document.querySelector('#dialogTitle').textContent=title;document.querySelector('#dialogSummary').textContent=s.summary||'Ingen oppsummering tilgjengelig ennå.';document.querySelector('#dialogWhy').textContent=s.whyItMatters||'';document.querySelector('#dialogSource').textContent=s.source||'nyhetskilden';const image=document.querySelector('#dialogImage');const url=localImageUrl(s);if(url){image.src=url;image.alt=`Bilde fra saken: ${title}`;image.style.display='block';image.onerror=()=>image.style.display='none'}else image.style.display='none';const list=document.querySelector('#dialogPoints');list.innerHTML='';(s.keyPoints||[]).filter(p=>!looksEnglish(p)).forEach(p=>{const li=document.createElement('li');li.textContent=p;list.appendChild(li)});const original=document.querySelector('#dialogOriginal');original.href=s.url||'#';original.style.display=s.url?'inline-flex':'none';dialog.showModal();document.body.classList.add('modal-open')}
function render(){const grid=document.querySelector('#newsGrid'),template=document.querySelector('#storyTemplate');const all=state.filter==='Alle'?state.stories:state.stories.filter(s=>s.category===state.filter);const stories=all.filter(usableStory);grid.innerHTML='';const count=document.querySelector('#storyCount');if(count)count.textContent='';if(!stories.length){grid.innerHTML='<div class="empty">Ingen saker med høy nok kvalitet og bilde i denne kategorien akkurat nå.</div>';return}stories.forEach((s,index)=>{const node=template.content.cloneNode(true),card=node.querySelector('.story-card');if(index===0&&state.filter==='Alle')card.classList.add('lead');if(isNew(s)){card.classList.add('is-new');const badge=document.createElement('span');badge.className='new-badge';badge.textContent='NY';node.querySelector('.story-topline').prepend(badge)}node.querySelector('.tag').textContent=s.category;node.querySelector('.time').textContent=`${relativeTime(s.publishedISO,s.published)} · ${readTime(s)}`;node.querySelector('.story-title').textContent=displayTitle(s);node.querySelector('.story-summary').textContent=s.summary;node.querySelector('.source').textContent=s.source?`Kilde: ${s.source}`:'';setImage(node.querySelector('.story-image'),node.querySelector('.story-image-wrap'),s);node.querySelector('.story-more').addEventListener('click',()=>openStory(s));grid.appendChild(node)})}
async function loadNews(){try{const r=await fetch(`${LIVE_DATA_URL}?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error('Kunne ikke hente nyhetsdata');const data=await r.json();state.stories=(data.stories||[]);document.querySelector('#lastUpdated').textContent=data.updatedAt?`Oppdatert ${data.updatedAt}`:'Oppdatert nå';render();localStorage.setItem(LAST_VISIT_KEY,String(Date.now()))}catch(e){console.error(e);document.querySelector('#lastUpdated').textContent='Kunne ikke hente siste oppdatering';document.querySelector('#newsGrid').innerHTML='<div class="empty">Prøv å laste siden på nytt om et øyeblikk.</div>'}}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;render()}));document.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>document.body.classList.remove('modal-open'));dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()});loadNews();setInterval(loadNews,2*60*1000);